### ISSUE TITLE
라이선스가 AGPL ?

### ISSUE THREAD

**Issue by wkpark** [koreapyj/php-namumark#1]
이거 라이선스 실수로 잘못 올린거 아닌가요? AGPLv3라니?

AGPLv3는 GPLv2 / GPLv3와 호환 안되는 라이선스입니다.
일부러 라이선스 고르더라도 이걸 선택하기는 쉽지 않았을텐데요.

http://www.gnu.org/licenses/license-list.html#AGPLv3.0

라이선스 잘 못 올린거 맞으시다면 GPLv2 라이선스와 호환 가능한 BSD 혹은 MIT 라이선스 계열을 추천합니다~

**Comment by koreapyj** [comment]
제대로 고른 것이 맞습니다. AGPL이므로 수정하여 사용할 때에는 코드를 공개해야 합니다. :)

**Comment by wkpark** [comment]
그렇다면 GPLv2 GPLv3도 있는데 왜 하필 GPL과 호환되지 않는 AGPL을 고르신 것인지요?

이렇게 하면 GPL 프로그램과 함께 묶어서 배포할 수 없습니다.
물론 사용자는 이걸 따로 받아서 설치해서 사용하는 것은 아무 문제가 없지만요.

널리 사용되는 GPL와 호환되고, 함께 묶어서 배포해도 문제가 없는 GPL을 선택하는 것은 어떠신지요?
